# Generated by Django 6.0.6 on 2026-07-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_projects', models.BooleanField(default=False)),
                ('can_manage_companies', models.BooleanField(default=False)),
                ('can_manage_groups', models.BooleanField(default=False)),
                ('can_create_projects', models.BooleanField(default=False)),
                ('can_edit_projects', models.BooleanField(default=False)),
                ('can_delete_projects', models.BooleanField(default=False)),
                ('can_create_tasks', models.BooleanField(default=False)),
                ('can_edit_tasks', models.BooleanField(default=False)),
                ('can_delete_tasks', models.BooleanField(default=False)),
                ('can_upload_files', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
    ]
