# Generated by Django 6.0.6 on 2026-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_role_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='can_delete_projects',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete_tasks',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_companies',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_groups',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_projects',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_users',
        ),
        migrations.AddField(
            model_name='role',
            name='can_invite_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_audit_logs',
            field=models.BooleanField(default=False),
        ),
    ]
