# Generated by Django 6.0.6 on 2026-07-17 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_role_can_delete_projects_and_more'),
        ('projects', '0006_projectdocument_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='projects.project'),
        ),
    ]
