# Generated by Django 6.0.6 on 2026-07-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
