# Generated by Django 6.0.6 on 2026-06-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='comment',
            new_name='content',
        ),
    ]
