# Generated by Django 6.0.6 on 2026-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_timeentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
