# Generated by Django 6.0.6 on 2026-06-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_timeentry_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='repeat_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
