# Generated by Django 6.0.6 on 2026-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_todoitem_is_recurring_todoitem_repeat_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
