# Generated by Django 6.0.6 on 2026-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_timeentry_end_time_timeentry_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
